fragment ItemListFields on Items {
  id
  name
  description
  item_picture{
    pictures{
      url
      previewUrl
    }
  }
  prices{
    price
  }
  # item_group{
  #   id
  # }
}

query GetItems($sort: String, $where: JSON!) {
  items(
    sort: $sort
    where: $where
  ) {
    ...ItemListFields
  }
}