# subscribe to added users
subscription ItemAdded($id: ID!) {
  itemAdded(id: $id) {
    id
    name
    description
  }
}

mutation addItem($name: String!, $description: String, $item_group: ID!) {
  createItem(
    input: {
      data: { name: $name, description: $description, item_group: $item_group }
    }
  ) {
    item {
      name
      description
    }
  }
}