# subscribe to added users
subscription ItemAdded($id: ID!) {
  itemAdded(id: $id) {
    id
    name
    description
  }
}

mutation addItem($name: String!, $description: String) {
  createItem(
    input: { data: { name: $name, description: $description } }
  ) {
    item {
      name
      description
    }
  }
}