query GetItems($sort: String, $search: String!) {
  items(
    sort: $sort
    where: { name_contains: $search }
  ) {
    id
    name
    item_picture{
      pictures{
        url
        previewUrl
      }
    }
    description
    created_at
  }
}