mutation updateItem(
  $id: ID!
  $name: String
  $description: String
  $price: [ID]
) {
  updateItem(
    input: {
      where: { id: $id }
      data: {
        name: $name
        description: $description
        created_by: 1
        prices: $price
      }
    }
  ) {
    item {
      name
    }
  }
}